### ISSUE TITLE
CI shutdown is unreliable

### ISSUE THREAD

**Issue by t-wissmann** [herbstluftwm/herbstluftwm#1448]
Sometimes, we get CI failures because hlwm takes too long to shut down after the big test case:
```
2022-02-11T17:31:27.4937618Z [gw0] [ 92%] ERROR tests/test_completion.py::test_completable_commands[False] 
2022-02-11T17:31:27.4938179Z 
2022-02-11T17:31:27.4938435Z ==================================== ERRORS ====================================
2022-02-11T17:31:27.4938803Z ____________ ERROR at teardown of test_completable_commands[False] _____________
2022-02-11T17:31:27.4939671Z [gw0] linux -- Python 3.8.10 /__w/herbstluftwm/herbstluftwm/.tox/py38/bin/python
2022-02-11T17:31:27.4940026Z 
2022-02-11T17:31:27.4940352Z hlwm_spawner = <function hlwm_spawner.<locals>.spawn at 0x7ff6a07c0d30>
2022-02-11T17:31:27.4941047Z request = <SubRequest 'hlwm_process' for <Function test_completable_commands[False]>>
2022-02-11T17:31:27.4941482Z xvfb = <conftest.MultiscreenDisplay object at 0x7ff6a0761520>
2022-02-11T17:31:27.4941715Z 
2022-02-11T17:31:27.4941826Z     @pytest.fixture()
2022-02-11T17:31:27.4942118Z     def hlwm_process(hlwm_spawner, request, xvfb):
2022-02-11T17:31:27.4942421Z         parameters = {
2022-02-11T17:31:27.4942883Z             'transparency': True,
2022-02-11T17:31:27.4943137Z         }
2022-02-11T17:31:27.4943538Z         if hasattr(request, 'param'):
2022-02-11T17:31:27.4944208Z             # the param must contain a dictionary possibly
2022-02-11T17:31:27.4944538Z             # updating the default parameters
2022-02-11T17:31:27.4944958Z             parameters.update(request.param)
2022-02-11T17:31:27.4945344Z     
2022-02-11T17:31:27.4945744Z         """Set up hlwm and also check that it shuts down gently afterwards"""
2022-02-11T17:31:27.4946309Z         additional_commandline = ['--no-tag-import']
2022-02-11T17:31:27.4946817Z         if not parameters['transparency']:
2022-02-11T17:31:27.4947352Z             additional_commandline += ['--no-transparency']
2022-02-11T17:31:27.4947896Z         hlwm_proc = hlwm_spawner(additional_commandline, display=xvfb.display)
2022-02-11T17:31:27.4948302Z     
2022-02-11T17:31:27.4948527Z         yield hlwm_proc
2022-02-11T17:31:27.4948843Z     
2022-02-11T17:31:27.4949091Z >       hlwm_proc.shutdown()
2022-02-11T17:31:27.4949255Z 
2022-02-11T17:31:27.4949999Z tests/conftest.py:614: 
2022-02-11T17:31:27.4950412Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2022-02-11T17:31:27.4950681Z 
2022-02-11T17:31:27.4950928Z self = <conftest.HlwmProcess object at 0x7ff6a084a520>
2022-02-11T17:31:27.4951138Z 
2022-02-11T17:31:27.4951341Z     def shutdown(self):
2022-02-11T17:31:27.4951705Z         self.proc.terminate()
2022-02-11T17:31:27.4952025Z     
2022-02-11T17:31:27.4952359Z         # Make sure to read and echo all remaining output (esp. ASAN messages):
2022-02-11T17:31:27.4952726Z         self.read_and_echo_output(until_eof=True)
2022-02-11T17:31:27.4953127Z         self.proc.stdout.close()
2022-02-11T17:31:27.4953506Z         self.proc.stderr.close()
2022-02-11T17:31:27.4953845Z     
2022-02-11T17:31:27.4954119Z         if self.proc.returncode is None:
2022-02-11T17:31:27.4954685Z             # only wait the process if it hasn't been cleaned up
2022-02-11T17:31:27.4955143Z             # this also avoids the second exception if hlwm crashed
2022-02-11T17:31:27.4955548Z             try:
2022-02-11T17:31:27.4956111Z >               assert self.proc.wait(PROCESS_SHUTDOWN_TIME) == 0
2022-02-11T17:31:27.4957156Z E               assert -13 == 0
2022-02-11T17:31:27.4957438Z E                 +-13
2022-02-11T17:31:27.4957695Z E                 -0
2022-02-11T17:31:27.4957846Z 
2022-02-11T17:31:27.4958119Z tests/conftest.py:461: AssertionError
2022-02-11T17:31:27.4985004Z ---------------------------- Captured stdout setup -----------------------------
2022-02-11T17:31:27.4986617Z Running: Xvfb -nolisten tcp -screen 0 800x600x24 -noreset +extension RENDER -displayfd 14
2022-02-11T17:31:27.4987018Z Xvfb is using the display ":1"
2022-02-11T17:31:27.4987427Z hlwm started
2022-02-11T17:31:27.4988059Z ---------------------------- Captured stderr setup -----------------------------
2022-02-11T17:31:27.4988542Z _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
2022-02-11T17:31:27.4989177Z _XSERVTransMakeAllCOTSServerListeners: server already running
2022-02-11T17:31:27.4989690Z EWMH: 0 desktops:
2022-02-11T17:31:27.4989924Z 0 managed clients: 
2022-02-11T17:31:27.4990361Z ../src/xconnection.cpp: 227: compositing manager = 0
2022-02-11T17:31:27.4990915Z ----------------------------- Captured stdout call -----------------------------
2022-02-11T17:31:27.4992224Z Client command ['try', 'true'] succeeded (no output)
2022-02-11T17:31:27.4992907Z Client command ['floating', 'status'] succeeded with output (output suppressed).
2022-02-11T17:31:27.4993424Z Client command ['floating', 'off'] succeeded (no output)

   [... shortened ...]


2022-02-11T17:31:27.7460813Z --------------------------- Captured stdout teardown ---------------------------
2022-02-11T17:31:27.7461047Z Client command ['version'] succeeded with output:
2022-02-11T17:31:27.7461254Z herbstluftwm 0.9.3 (5517222 built on 2022-02-11)
2022-02-11T17:31:27.7462130Z Copyright (c) 2011-2021 Thorsten Wißmann
2022-02-11T17:31:27.7462279Z Released under the Simplified BSD License
2022-02-11T17:31:27.7462382Z xrandr support: on
2022-02-11T17:31:27.7462723Z xinerama support: on
2022-02-11T17:31:27.7462735Z 
2022-02-11T17:31:27.7463082Z --------------------------- Captured stderr teardown ---------------------------
2022-02-11T17:31:27.7463197Z interrupted by signal 15
2022-02-11T17:31:27.7463350Z ============================= slowest 10 durations =============================
2022-02-11T17:31:27.7463550Z 188.09s call     tests/test_completion.py::test_completable_commands[False]
2022-02-11T17:31:27.7463769Z 17.77s teardown tests/test_completion.py::test_completable_commands[False]
2022-02-11T17:31:27.7464069Z 12.06s call     tests/test_completion.py::test_junk_args_dont_crash[junk-2]
2022-02-11T17:31:27.7464411Z 11.69s call     tests/test_completion.py::test_junk_args_dont_crash[234-2]
2022-02-11T17:31:27.7464691Z 11.13s call     tests/test_completion.py::test_junk_args_dont_crash[ -2]
2022-02-11T17:31:27.7464975Z 7.90s call     tests/test_completion.py::test_junk_args_dont_crash[234-1]
2022-02-11T17:31:27.7465261Z 7.78s call     tests/test_completion.py::test_junk_args_dont_crash[junk-1]
2022-02-11T17:31:27.7465538Z 7.66s call     tests/test_completion.py::test_junk_args_dont_crash[ -1]
2022-02-11T17:31:27.7465801Z 4.13s call     tests/test_completion.py::test_junk_args_dont_crash[234-0]
2022-02-11T17:31:27.7466079Z 4.05s call     tests/test_completion.py::test_junk_args_dont_crash[ -0]
2022-02-11T17:31:27.7466235Z =========================== short test summary info ============================
2022-02-11T17:31:27.7466696Z ERROR tests/test_completion.py::test_completable_commands[False] - assert -13...
2022-02-11T17:31:27.7466943Z !!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-02-11T17:31:27.7467145Z !!!!!!!!!!!! xdist.dsession.Interrupted: stopping after 1 failures !!!!!!!!!!!!!
2022-02-11T17:31:27.7467298Z =================== 12 passed, 1 error in 211.01s (0:03:31) ====================
2022-02-11T17:31:27.7467472Z Traceback (most recent call last):
2022-02-11T17:31:27.7467609Z   File "ci/build.py", line 155, in <module>
2022-02-11T17:31:27.7467906Z     tox('-- -n auto -v -x --durations=10 -m exclude_from_coverage', build_dir)
2022-02-11T17:31:27.7468030Z   File "ci/build.py", line 17, in tox
2022-02-11T17:31:27.7468310Z     sp.check_call(f'tox {tox_args}', shell=True, cwd=build_dir, env=tox_env)
2022-02-11T17:31:27.7468484Z   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
2022-02-11T17:31:27.7468630Z     raise CalledProcessError(retcode, cmd)
2022-02-11T17:31:27.7469134Z subprocess.CalledProcessError: Command 'tox -- -n auto -v -x --durations=10 -m exclude_from_coverage' returned non-zero exit status 1.
2022-02-11T17:31:27.7469701Z ERROR: InvocationError for command /__w/herbstluftwm/herbstluftwm/.tox/py38/bin/python -m pytest -n auto -v -x --durations=10 -m exclude_from_coverage (exited with code 2)
2022-02-11T17:31:27.7469845Z ___________________________________ summary ____________________________________
2022-02-11T17:31:27.7469963Z ERROR:   py38: commands failed
2022-02-11T17:31:27.7481912Z ##[error]Process completed with exit code 1.
2022-02-11T17:31:27.7552978Z Post job cleanup.
2022-02-11T17:31:27.7555900Z ##[command]/usr/bin/docker exec  d5eebcff9884d6e29ca57a1ad7904731cc006b507672b974c73565075d928fab sh -c "cat /etc/*release | grep ^ID"
2022-02-11T17:31:28.1793337Z [command]/usr/bin/git version
2022-02-11T17:31:28.1875590Z git version 2.25.1
2022-02-11T17:31:28.1933211Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-02-11T17:31:28.2018033Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-02-11T17:31:28.2431354Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-02-11T17:31:28.2475591Z http.https://github.com/.extraheader
2022-02-11T17:31:28.2485949Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2022-02-11T17:31:28.2531300Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2022-02-11T17:31:28.3067332Z Stop and remove container: 6103d33296f04be484f046a02d33a248_hlwmcifocal_70c082
2022-02-11T17:31:28.3074586Z ##[command]/usr/bin/docker rm --force d5eebcff9884d6e29ca57a1ad7904731cc006b507672b974c73565075d928fab
2022-02-11T17:31:28.9180524Z d5eebcff9884d6e29ca57a1ad7904731cc006b507672b974c73565075d928fab
2022-02-11T17:31:28.9222776Z Remove container network: github_network_b1bede6a67bc4d37bac1b8d1bf144544
2022-02-11T17:31:28.9230039Z ##[command]/usr/bin/docker network rm github_network_b1bede6a67bc4d37bac1b8d1bf144544
2022-02-11T17:31:29.0551470Z github_network_b1bede6a67bc4d37bac1b8d1bf144544
2022-02-11T17:31:29.0857273Z Cleaning up orphan processes
```

**Comment by t-wissmann** [comment]
Lets see whether #1467 helps.
