### ISSUE TITLE
Crash for unknown reason (herbstclient? mouse selection?)

### ISSUE THREAD

**Issue by t-wissmann** [herbstluftwm/herbstluftwm#590]
I just quickly switched between my mail client (in urxvt) and the q3terminal.sh in order to copy some text out of the mail client to the urxvt in the q3terminal when herbstluftwm suddenly segfaultet. This here is the backtrace:
```
#0  0x00007ffff7877823 in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
#1  0x00007ffff7b7dc71 in std::char_traits<char>::copy (__n=81, __s2=0x1ad122 <error: Cannot access memory at address 0x1ad122>, __s1=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:365
#2  std::basic_streambuf<char, std::char_traits<char> >::xsputn (this=0x7fffffffdfd8, __s=0x1ad122 <error: Cannot access memory at address 0x1ad122>, __n=81) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/streambuf.tcc:90
#3  0x00007ffff7b6c22b in std::basic_streambuf<char, std::char_traits<char> >::sputn (__n=81, __s=<optimized out>, this=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/streambuf:457
#4  std::__ostream_write<char, std::char_traits<char> > (__n=81, __s=<optimized out>, __out=...) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream_insert.h:50
#5  std::__ostream_insert<char, std::char_traits<char> > (__out=..., __s=0x1ad122 <error: Cannot access memory at address 0x1ad122>, __n=81) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream_insert.h:101
#6  0x000055555565c526 in std::operator<< <char, std::char_traits<char>, std::allocator<char> > (__str=..., __os=...) at /usr/include/c++/8.3.0/bits/basic_string.h:6323
#7  MonitorManager::<lambda(Input, Output)>::operator() (output=..., input=..., __closure=0x555555814290) at /home/thorsten/git/winterbreeze-live-test/src/monitormanager.cpp:179
#8  std::_Function_handler<int(Input, std::basic_ostream<char, std::char_traits<char> >&), MonitorManager::byFirstArg(MonitorCommand)::<lambda(Input, Output)> >::_M_invoke(const std::_Any_data &, Input &&, std::basic_ostream<char, std::char_traits<char> > &) (__functor=..., __args#0=..., __args#1=...)
    at /usr/include/c++/8.3.0/bits/std_function.h:282
#9  0x00005555555f2f48 in std::function<int (Input, std::ostream&)>::operator()(Input, std::ostream&) const (__args#1=..., __args#0=..., this=0x555555814238) at /usr/include/c++/8.3.0/bits/std_function.h:682
#10 CommandBinding::operator() (out=..., args=..., this=0x555555814238) at /home/thorsten/git/winterbreeze-live-test/src/command.h:97
#11 CommandTable::callCommand (this=this@entry=0x5555557f53e0, args=..., out=...) at /home/thorsten/git/winterbreeze-live-test/src/command.cpp:308
#12 0x00005555555f33f7 in Commands::call (args=..., out=...) at /usr/include/c++/8.3.0/ext/atomicity.h:96
#13 0x00005555556328f0 in HlwmCommon::callCommand (call=std::vector of length 2, capacity 2 = {...}) at /usr/include/c++/8.3.0/ext/atomicity.h:96
#14 0x00005555556bd4fc in std::_Function_handler<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&), std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (*)(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)>::_M_invoke(std::_Any_data const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (__functor=..., __args#0=...)
    at /usr/include/c++/8.3.0/bits/std_function.h:88
#15 0x0000555555637415 in std::function<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)>::operator()(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const (__args#0=std::vector of length 2, capacity 2 = {...}, this=0x7fffffffe2c0)
    at /usr/include/c++/8.3.0/bits/std_function.h:682
#16 IpcServer::handleConnection(unsigned long, std::function<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)>) (this=0x5555557da450, win=25165825, callback=...) at /home/thorsten/git/winterbreeze-live-test/src/ipc-server.cpp:65
#17 0x00005555556bb097 in XMainLoop::propertynotify (this=0x7fffffffe500, ev=0x7fffffffe3b0) at /usr/include/c++/8.3.0/new:169
#18 0x00005555556bbaa8 in XMainLoop::run (this=0x7fffffffe500) at /home/thorsten/git/winterbreeze-live-test/src/xconnection.h:17
#19 0x00005555555cdcbe in main (argc=<optimized out>, argv=0x7fffffffe878) at /home/thorsten/git/winterbreeze-live-test/src/main.cpp:501
```
I was on commit 68199bd25cb0d844c59d6b3b62c89952982d5620 and I can also provide the core dump if anyone is particularly interested.

**Comment by t-wissmann** [comment]
```
#7  MonitorManager::<lambda(Input, Output)>::operator() (output=..., input=..., __closure=0x555555814290)
at /home/thorsten/git/winterbreeze-live-test/src/monitormanager.cpp:179
```
was indeed the cause of the crash:
```c++
    return [this,cmd](Input input, Output output) -> int {
        Monitor *monitor;
        string monitor_name;
        if (!(input >> monitor_name)) {
            monitor = get_current_monitor();
        } else {
            monitor = byString(monitor_name);
            if (!monitor) {
                output << input.command() <<
                    ": Monitor \"" << input.front() << "\" not found!\n";  // line 179
                return HERBST_INVALID_ARGUMENT;
            }
        }
        return cmd(*monitor, Input(input.command(), input.toVector()), output);
    };
```
